### ISSUE TITLE
Addon Doesn't Load

### ISSUE THREAD

**Issue by MatthewLAllen** [Nighthawk42/wow_bejeweled#1]
At launch or reload an error is display that at line 384 of the lua file, 7.3.5 is a malformed number.  I have tried editing this file to see if there are any nonvisible characters near this version number but it did not seem to make a difference.  Can you help figure out why this isn't working as expected?  I am running windows 10 with a moderate number of other addons that are all loading as expected.

**Comment by MatthewLAllen** [comment]
It is trying to convert 7.3.5 into  a double so that won't work and prevents the addon from loading.  in my local File I change line 384 and 3465 from 7.3.5 to 7.35 and now the addon loads as expected although it now throws a different error when getting on a flight path.  that one looks more involved so if I try and fix that i will submit a pull request.

**Comment by Ecilam** [comment]
In Bejeweled.lua file, Lines 384 and 3465 : replace 7.3.5 by "7.3.5"

**Comment by Nighthawk42** [comment]
Issue is fixed as of latest commit.
