### ISSUE TITLE
Classic version dosent work for Turtle WoW :C

### ISSUE THREAD

**Issue by sumpjumper** [Nighthawk42/wow_bejeweled#11]
anychance you would be able to port/fix would be really cool :)

**Comment by Nighthawk42** [comment]
I'm no longer maintaining the addon as it has grown beyond my current Lua abilities. 

Given that Turtle WoW is a private server with custom client changes I can't say what might be broken. Most likely changes that happened between 7.x and 10.x - As for the Classic version, it has major UI changes over the original vanilla clients as well. 

Turtle WoW seems to be based on the 3.3.5 client, I'd suggest using the old, untouched original from PopCap here on [Curse](https://www.wowinterface.com/downloads/info11019-Bejeweled.html). It may complain about the TOC version being out of date, just load it anyway. 

Kautzman's [fork](https://github.com/Kautzman/wow_bejeweled) should be considered the de facto successor to this repo. Eventually I plan to archive it to read-only.

**Comment by sambonz** [comment]
Apologies for messaging here but I'm not a GitHub user and I don't know how to contact Kautzman directly or to post an issue. I downloaded his fork (thank you) and it's working great except for that it blocks screenshots (a Blizz error pops up mentioning preventing an action).
Feel free to delete this if it's inappropriate to write here, but how do I get feedback on the issue to the fork creator please? Thank you!

**Comment by Nighthawk42** [comment]
@sambonz The same way you did here. Go to his repo using the URL above, go to _Issues_ and create one.
